[ARTS-527] Init service client connects to other services using discovery server
NDPH-ARTS/mts-services pull request #153
Opened 2021-02-24 11:26 UTC by anatbal

## Description
Client implementation of connectivity between the init service and the rest of the services.

### Changes
- [ARTS-527] - Init using discovery server in order to connect to other services

### Checks
- [ ]  Run docker-compose with 'local' profile
- [ ] Run docker-compose with 'dev' profile
- [ ] Run on Azure test environment

### Checklist:
- [x] Branch name follows convention (feature/arts-#-short-name OR fix/arts-#-short-name)
- [x] I have included a short-meaningful title, description and changes for this PR

2021-02-28 06:19 UTC, tamirkamara requested changes

2021-02-28 08:26 UTC, anatbal commented on init-service/src/main/resources/bootstrap.yml
> -      fail-fast: true
We removed it in all of the other services  so I figured it should not be in the init as well... WDYT?

2021-02-28 08:56 UTC, eladiw submitted a review, later dismissed

2021-03-01 07:42 UTC, eladiw submitted a review, later dismissed

2021-03-01 19:55 UTC, darrengsmithson submitted a review, later dismissed

2021-03-03 09:02 UTC, eladiw submitted a review, later dismissed

2021-03-03 15:11 UTC, eladiw approved these changes

2021-03-03 19:18 UTC, darrengsmithson approved these changes

2021-03-03 19:45 UTC, merged