[ARTS-758] - Adding schema generation for all services (part 1)
NDPH-ARTS/mts-services pull request #207
Opened 2021-03-22 18:35 UTC by eladiw

## Description
This is a first part for ARTS 758 - Allowing schema validations at CI.
This PR updates the build-tools, which now generates several configuration files instead of just the definition file.
The next PR (in the deployment repository) will consist of taking the generated schemas and adding a CI workflow step that verifies all given config files with the schemas.

### Changes
- [ARTS-758] - Adding the option to generate all configuration files

### Checklist:

- [ ] Branch name follows convention (feature/arts-#-short-name OR fix/arts-#-short-name)
- [ ] I have included a short-meaningful title, description and changes for this PR

2021-03-25 08:56 UTC, anatbal approved these changes
LGTM

2021-03-29 14:20 UTC, tamirkamara requested changes

2021-03-29 14:20 UTC, tamirkamara commented on build-tools/src/main/java/uk/ac/ox/ndph/mts/json_schema_generator/Main.java
> +        private Class cls;
```suggestion
        private final Class<?> cls;
```

2021-03-29 14:20 UTC, tamirkamara commented on build-tools/src/main/java/uk/ac/ox/ndph/mts/json_schema_generator/Main.java
> +        private String filename;
```suggestion
        private final String filename;
```

2021-03-29 14:20 UTC, tamirkamara commented on build-tools/src/main/java/uk/ac/ox/ndph/mts/json_schema_generator/Main.java
> +            new GeneratedTuple(SiteConfig.class, "site-service-configuration-schema.json"));
I think this is simpler and would remove the google dependency:
` List<GeneratedTuple> itemToProcess = Arrays.asList(x, y...);`

2021-03-29 14:20 UTC, tamirkamara commented on build-tools/src/main/java/uk/ac/ox/ndph/mts/json_schema_generator/Main.java
> +        public Class getCls() {
```suggestion
        public Class<?> getCls() {
```

2021-03-29 14:20 UTC, tamirkamara commented on build-tools/src/main/java/uk/ac/ox/ndph/mts/json_schema_generator/Main.java
> +        public GeneratedTuple(Class cls, String filename) {
```suggestion
        public GeneratedTuple(Class<?> cls, String filename) {
```

2021-03-29 14:20 UTC, tamirkamara commented on build-tools/src/main/java/uk/ac/ox/ndph/mts/json_schema_generator/Main.java
> +            new GeneratedTuple(SiteConfig.class, "site-service-configuration-schema.json"));
Since the classes are anyway on this module, what do you think about a property for the schema name and "ignore" it in the serialization?

2021-03-29 14:20 UTC, tamirkamara commented on build-tools/src/main/java/uk/ac/ox/ndph/mts/json_schema_generator/model/InitTrialConfig.java
> +public class InitTrialConfig {
I think you should add a java doc here to explain what this class is for and why an internal Mts one. Also valid for the other classes.

2021-04-04 11:35 UTC, tamirkamara approved these changes

2021-04-04 11:36 UTC, anatbal approved these changes

2021-04-04 11:36 UTC, merged