[ARTS-756] Init service uses shared role client
NDPH-ARTS/mts-services pull request #209
Opened 2021-03-24 08:38 UTC by anatbal

## Description
- [ ] Init uses the shared role service client
- [ ] Run on AZ

### Changes
- [ARTS-756] - Services use the shared role client

### Checklist:

- [x] Branch name follows convention (feature/arts-#-short-name OR fix/arts-#-short-name)
- [x] I have included a short-meaningful title, description and changes for this PR

2021-03-29 12:08 UTC, tamirkamara requested changes

2021-03-29 13:34 UTC, shajidissa submitted a review, later dismissed

2021-03-29 16:25 UTC, anatbal commented on role-service-client/pom.xml
> +        </dependency>
After discussing with Liza about Authz I reverted it to the as it was before, we don't need it

2021-03-29 16:25 UTC, anatbal commented on role-service-client/pom.xml
> +            <scope>compile</scope>
Same as above

2021-03-29 16:25 UTC, anatbal commented on role-service-client/src/main/java/uk/ac/ox/ndph/mts/roleserviceclient/RequestExecutor.java
> +                    httpStatus -> !httpStatus.is2xxSuccessful(),
Fixed

2021-03-30 08:13 UTC, shajidissa approved these changes

2021-03-31 08:17 UTC, shajidissa approved these changes

2021-03-31 08:30 UTC, merged