[ARTS-884] Validate configuration classes
NDPH-ARTS/mts-services pull request #228
Opened 2021-03-31 13:50 UTC by tamirkamara

## Description
This PR adds validation on the java classes themselves and results in detailed errors on load time if the fetched config doesn't fit the classes (rather than just dependency injection errors like before).

### Changes
- [ARTS-884] - Config classes validation

### Checklist:

- [ ] Branch name follows convention (feature/arts-#-short-name OR fix/arts-#-short-name)
- [ ] I have included a short-meaningful title, description and changes for this PR

2021-04-04 07:00 UTC, eladiw commented on site-service/src/main/java/uk/ac/ox/ndph/mts/site_service/model/SiteAttributeConfiguration.java
> +    @NotBlank
why type and regex are not annotated?

2021-04-04 07:01 UTC, eladiw commented on practitioner-service/src/main/java/uk/ac/ox/ndph/mts/practitioner_service/model/PractitionerAttributeConfiguration.java
> +    @NotBlank
why validation regex is not annotated?

2021-04-04 07:03 UTC, eladiw requested changes
looks good. minor comment

2021-04-04 08:19 UTC, eladiw approved these changes

2021-04-04 08:31 UTC, tamirkamara commented on site-service/src/main/java/uk/ac/ox/ndph/mts/site_service/model/SiteAttributeConfiguration.java
> +    @NotBlank
Because those aren't always filled.

2021-04-04 08:31 UTC, tamirkamara commented on practitioner-service/src/main/java/uk/ac/ox/ndph/mts/practitioner_service/model/PractitionerAttributeConfiguration.java
> +    @NotBlank
Because those aren't always filled.

2021-04-06 06:22 UTC, eladiw approved these changes

2021-04-06 08:52 UTC, shajidissa approved these changes

2021-04-06 11:08 UTC, merged