[ARTS-764] Authorise to retrieve only permission roles  the user is assigned to
NDPH-ARTS/mts-services pull request #247
Opened 2021-04-08 06:26 UTC by LizaShak

## Description
Restrict access to get permission roles. Authorise only if all the permission roles are roles that the user is assigned to.

### Changes
- [ARTS-764] - Get my roles
- Integrate security package in role service
- Add authorisation header on get roles by ids
- Authorise only if all the permission roles are roles that the user is assigned to

### Checklist:

- [ ] Branch name follows convention (feature/arts-#-short-name OR fix/arts-#-short-name)
- [ ] I have included a short-meaningful title, description and changes for this PR

2021-04-08 15:02 UTC, darrengsmithson submitted a review, later dismissed

2021-04-09 07:59 UTC, sameerapurini commented
Hi @LizaShak I have added updates to api tests as part of my pr raised into yours, not sure why the same code has been copied over to your branch please

2021-04-11 10:50 UTC, anatbal requested changes

2021-04-11 10:50 UTC, anatbal commented on role-service-client/src/test/java/uk/ac/ox/ndph/mts/roleserviceclient/CreateEntityTest.java
> +    private String token = "some-token";
```suggestion
    private String token = "some-token";
    private Consumer<HttpHeaders> authHeaders = RoleServiceClient.bearerAuth(token);
```
Then we can replace all RoleServiceClient.bearerAuth(token) with authHeaders

2021-04-11 10:50 UTC, anatbal commented on role-service-client/src/test/java/uk/ac/ox/ndph/mts/roleserviceclient/FindByIdTest.java
> +    private String token = "some-token";
Same comment

2021-04-11 10:50 UTC, anatbal commented on role-service-client/src/test/java/uk/ac/ox/ndph/mts/roleserviceclient/FindByIdsTest.java
> +    private String token = "some-token";
Same comment

2021-04-11 10:50 UTC, anatbal commented on role-service-client/src/test/java/uk/ac/ox/ndph/mts/roleserviceclient/FindPageTest.java
> +    private String token = "some-token";
Same comment

2021-04-11 10:50 UTC, anatbal commented on role-service-client/src/test/java/uk/ac/ox/ndph/mts/roleserviceclient/UpdatePermissionsTest.java
> +    private final String token = "some-token";
Same comment

2021-04-11 12:25 UTC, anatbal submitted a review, later dismissed

2021-04-12 07:17 UTC, anatbal submitted a review, later dismissed

2021-04-12 08:44 UTC, darrengsmithson submitted a review, later dismissed

2021-04-12 11:50 UTC, anatbal approved these changes

2021-04-12 12:16 UTC, darrengsmithson approved these changes

2021-04-12 12:16 UTC, merged