add github action to build
NDPH-ARTS/mts-services pull request #3
Opened 2020-12-23 16:04 UTC by itye-msft

this action will trigger a ci on new PR and on merge

2020-12-23 16:08 UTC, tamirkamara approved these changes

2020-12-23 17:21 UTC, marrobi commented
@itye-msft have you seen the work @shajidissa and @mdp0 have done here https://github.com/NDPH-ARTS/trial-config-service/blob/main/.github/workflows/pr-test.yml? The build and tests are happening within Docker. 

Should probably stick with one approach. I like the Docker approach, as I can build locally with no prerequisites, but happy to be convinced otherwise!

2020-12-23 18:15 UTC, itye-msft commented
> @itye-msft have you seen the work @shajidissa and @mdp0 have done here https://github.com/NDPH-ARTS/trial-config-service/blob/main/.github/workflows/pr-test.yml? The build and tests are happening within Docker.
> 
> Should probably stick with one approach. I like the Docker approach, as I can build locally with no prerequisites, but happy to be convinced otherwise!

I havn't seen it, and it looks good, aside of the the problem, that this yaml file should build all the projects inside the repo...

2020-12-23 18:21 UTC, marrobi commented
Hmm. Is each microservice not going to be built independently/have its own pipeline and tests? 

Guess could build the entire repo and then take the jar files, but could be building (and testing) lots that's isn't needed.

2020-12-23 18:25 UTC, itye-msft commented
> Hmm. Is each microservice not going to be built independently/have its own pipeline and tests?
> 
> Guess could build the entire repo and then take the jar files, but could be building (and testing) lots that's isn't needed.

The CI doesn't know all microservices are placed in the same repo. As far as it cares, there was a change which triggers a CI and now it builds... everything

2020-12-23 19:34 UTC, marrobi commented
As discussed, if this is just a placeholder until other pipelines are added then that's fine.

Suggest  a repo wide CI approach is agreed and this removed when resulting pipeline(s) are added.

2020-12-24 11:35 UTC, LizaShak requested changes

2020-12-24 11:35 UTC, LizaShak commented on .github/workflows/docker-build-push.yml
> +          docker push ghcr.io/ndph-arts/trial-config-service:${{ github.sha }}
shouldn't it  be sample-service?

2020-12-24 11:35 UTC, LizaShak commented on .github/workflows/docker-build-push.yml
> +name: Docker build and push
I can't comment on the file, but we need to add the .DS_Store to gitignore file

2020-12-27 08:16 UTC, LizaShak approved these changes

2020-12-27 08:19 UTC, merged