Feature/arts 301 site service add parent
NDPH-ARTS/mts-services pull request #47
Opened 2021-01-15 10:32 UTC by kedarl-rdb

## Description
Site Service Add Parent (ARTS-175)

### Changes
- ARTS-301 - Verify Organisation can connect to a parent. The Parent is optional.

2021-01-15 11:12 UTC, shajidissa commented
Kedar, merge main into this and assign reviewers.

2021-01-18 18:22 UTC, darrengsmithson requested changes

2021-01-18 18:38 UTC, shajidissa requested changes

2021-01-18 18:38 UTC, shajidissa commented on api-test/config/conf.js
> +
All files in api-tests should not show in your PR as you've not added them. These should be what is in main branch.

2021-01-18 18:38 UTC, shajidissa commented on site-service/src/main/java/uk/ac/ox/ndph/mts/site_service/configuration/SiteAttribute.java
> +@Getter
This is related to ARTS-376

2021-01-18 18:38 UTC, shajidissa commented on site-service/src/main/java/uk/ac/ox/ndph/mts/site_service/configuration/SiteConfiguration.java
> +public class SiteConfiguration {
This is related to ARTS-376

2021-01-18 18:38 UTC, shajidissa commented on site-service/src/main/java/uk/ac/ox/ndph/mts/site_service/model/Site.java
> +@Getter
This is related to ARTS-376

2021-01-18 18:38 UTC, shajidissa commented on trial-config-service/Dockerfile
>  COPY ./sample-service/pom.xml ./sample-service/pom.xml
files in trial-config-service should not be part of your PR.

2021-01-20 07:13 UTC, kedarl-rdb commented
Closing this obsolete PR
New PR has been raised

2021-01-20 07:13 UTC, kedarl-rdb commented
Closing this obsolete PR
New PR has been raised

2021-01-20 07:13 UTC, closed without merging